<?php /** @var \Magento\Framework\View\Element\Template $block */ ?> <div class="block block-dashboard-info"><div class="block-title"><strong><?= $block->escapeHtml(__('Current User Time')) ?></strong></div><div class="block-content"><div class="box-content"><p id="user-clock" style="font-size:18px; font-weight:bold; margin:0;"></p></div></div></div><script>
require(['jquery'], function ($) {
    function updateClock() {
        const now = new Date();

        const options = {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        };

        const dateString = now.toLocaleDateString(undefined, options);

        let h = String(now.getHours()).padStart(2, '0');
        let m = String(now.getMinutes()).padStart(2, '0');
        let s = String(now.getSeconds()).padStart(2, '0');

        const timeString = `${h}:${m}:${s}`;

        $('#user-clock').text(`${dateString} \r\n ${timeString}`);
    }

    updateClock();
    setInterval(updateClock, 1000);
});</script>